FORMAT: 1A

# User API
The user API is a collection of services related to the users data. Those services can be 
used to register a new user, create, update and delete user data e.g. name, address.

## Complete list of user properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a user. Choosen automatically. | None (not editable) |
| address     |  Array[Object]     | Array of address objects. | See address properties for more informations. | 0 | 10 |
| company     |  String     | Company name. | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| country     |  Enum     | Country the user is from. | Must be [ISO-3166-1](https://github.com/ndheitypi/AblIMardEA-Users/wiki/Country-Codes) | 3 | 3 |
| email     |  String     | Email address. Used to login. | Unique. Well-formed email address. | 5 | 50 |
| firstname1 |  String     | 1. First name | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |
| firstname2 |  String     | 2. First name | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| firstname3 |  String     | 3. First name | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| gender     |  Enum     | Gender | One of: M,W | 1 | 1 |
| language     |  Enum     | Preffered language for this website. | One of: DE,EN,ES,FR | 2 | 2 |
| lastname     |  String     | Last name. | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |
| password     |  String     | The user password. | Pattern: [0-9a-zA-Z_-] | 5 | 50 |
| username     |  String     | Username. | Unique. Pattern: [0-9a-zA-Z_-] | 3 | 100 |

## Complete list of address properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| country     |  String     | Country | Must be [ISO-3166-1](https://github.com/ndheitypi/AblIMardEA-Users/wiki/Country-Codes) | 3 | 3 |
| default |  Boolean     | Default address. Always true when there is only on address. | Not null. | 1 | 1 |
| postcode |  String     | Postcode | Pattern: [0-9] | 3 | 10 |
| phone |  String     | Phone | Pattern: [0-9.+-()] + whitespace | 0 | 50 |
| street     |  String     | Street | Pattern: [0-9a-zA-Z_-] + whitespace | 3 | 100 |
| street2     |  String     | Additional address informations. | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| suburb     |  String     | Suburb | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| town |  String     | Town | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |

# Group Users

## Users Collection [/users]
### List all Campaigns [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Advertise new product XYZ."
        }, {
          "id": 2, "title": "Advertise 50% discount of product XYZ."
        }]

