FORMAT: 1A

# User API
The user API is a collection of services related to the users data. Those services can be 
used to register a new user, create, update and delete user data e.g. name, address.

# Appendix
Property can be left empty if minimum length equals zero.

## User properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| id     |  String     | Public id to identify a user. Choosen automatically. | None (not editable) |
| address     |  Array[Object]     | Array of address objects. | See address properties for more informations. | 0 | 10 |
| company     |  String     | Company name. | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| country     |  Enum     | Country the user is from. | Must be [ISO-3166-1](https://github.com/ndheitypi/AblIMardEA-Users/wiki/Country-Codes) | 3 | 3 |
| email     |  String     | Email address. Used to login. | Unique. Well-formed email address. | 5 | 50 |
| firstname1 |  String     | 1. First name | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |
| firstname2 |  String     | 2. First name | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| firstname3 |  String     | 3. First name | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| gender     |  Enum     | Gender | One of: M,W | 1 | 1 |
| language     |  Enum     | Preffered language for this website. | One of: DE,EN,ES,FR | 2 | 2 |
| lastname     |  String     | Last name. | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |
| password     |  String     | The user password. | Pattern: [0-9a-zA-Z_-] | 5 | 50 |
| username     |  String     | Username. | Unique. Pattern: [0-9a-zA-Z_-] | 3 | 100 |

## Address properties

| Name      |      Type         |  Description  | Constraints | Min.-Length | Max.-Length |
|----------|:-------------:|:------:|------|:------:|------|------|
| country     |  String     | Country | Must be [ISO-3166-1](https://github.com/ndheitypi/AblIMardEA-Users/wiki/Country-Codes) | 3 | 3 |
| default |  Boolean     | Default address. Always true when there is only on address. | Not null. | 1 | 1 |
| postcode |  String     | Postcode | Pattern: [0-9] | 3 | 10 |
| phone |  String     | Phone | Pattern: [0-9.+-()] + whitespace | 0 | 50 |
| street     |  String     | Street | Pattern: [0-9a-zA-Z_-] + whitespace | 3 | 100 |
| street2     |  String     | Additional address informations. | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| suburb     |  String     | Suburb | Pattern: [0-9a-zA-Z_-] + whitespace | 0 | 100 |
| town |  String     | Town | Pattern: [0-9a-zA-Z_-] + whitespace | 2 | 100 |

# Group Users
## List all users [/admin/users]
| Name      |      Content         | 
|----------|:-------------:|
| URL:     |  /admin/users     | 
| Request-Type:     |  GET     | 
| Request-Body:     |  Optional     | 
| Required permission:     |  Administrator |

Returns a list containing all users if the request body is empty. The user list can be searched and filtered by sending a search body. 
### Get users [GET]
+ Response 200 (application/json)

        {
            "paging": {
                "page": 1
                "pagesize": 10
                "totalcount": 2
            },
            "list": [{
              "id": "XZSDGWUZTGSJDGZU"
              ,"country": null
              ,"language": "EN"
              ,"email": "john@test.com"
              ,"firstname1": "John"
              ,"lastname": "Doe"
              ,"username": "johndoe"
            }, {
              "id": "XZSDGWUZTGSJDGAB"
              ,"country": null
              ,"language": "EN"
              ,"email": "jane@test.com"
              ,"firstname1": "Jane"
              ,"lastname": "Doe"
              ,"username": "janedoe"
            }]
        }
        
## Show public user profile [/users/{user_id}]
| Name      |      Content         | 
|----------|:-------------:|
| URL:     |  /users/{user_id}     | 
| Request-Type:     |  GET     | 
| Request-Body:     |  None     | 
| Required permission:     |  None |

Returns a list containing all users if the request body is empty. The user list can be searched and filtered by sending a search body. 

+ Parameters
    + user_id (required, string, `XZSDGWUZTGSJDGZU`) ... ID of the user in form of an string.

### Get users [GET]
+ Response 200 (application/json)

        {
            "user": {
              "id": "XZSDGWUZTGSJDGZU"
              ,"country": null
              ,"firstname1": "John"
              ,"lastname": "Doe"
              ,"username": "johndoe"
            }
        }